version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: sql_ex_db
      POSTGRES_USER: boomzin
      POSTGRES_PASSWORD: boomzin
    ports:
      - "5432:5432"
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  flyway:
    container_name: flyway
    build:
      context: ./
      dockerfile: ./docker/flyway/Dockerfile
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./db/migration/:/flyway/sql:ro
    depends_on:
      - postgres
    networks:
      - sql-ex-network

networks:
  sql-ex-network:
    driver: bridge

volumes:
  pgdata:
