CREATE TABLE painting.utQ (
    Q_ID SERIAL PRIMARY KEY,
    Q_NAME VARCHAR(35) NOT NULL
);

CREATE TABLE painting.utV (
    V_ID SERIAL PRIMARY KEY,
    V_NAME VARCHAR(35) NOT NULL,
    V_COLOR VARCHAR(35) NOT NULL
);

CREATE TABLE painting.utB (
    B_DATETIME TIMESTAMP NOT NULL,
    B_Q_ID INTEGER NOT NULL REFERENCES painting.utQ(Q_ID),
    B_V_ID INTEGER NOT NULL REFERENCES painting.utV(V_ID),
    B_VOL SMALLINT NOT NULL,
    PRIMARY KEY (B_DATETIME, B_Q_ID, B_V_ID)
);